<?php echo $this->renderTabs($this->tabs); ?>
<?php echo $this->renderList($this->list); ?>
<div class="list">
    <table><tr>
    <?php foreach (['insecure', 'letsencrypt', 'ok'] as $status): ?>
    <td>
        <img src="<?php echo pm_Context::getBaseUrl() . "/images/ssl-{$status}.png" ?>">
        <?php echo $this->lmsg('list.domains.status' . ucfirst($status)) ?>
    </td>
    <?php endforeach ?>
    </tr></table>
</div>
