<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<?php echo $this->renderTabs($this->tabs); ?>

<script type="text/javascript">
    function show_busy(eid) {
        var e = document.getElementById(eid);
        e.innerHTML = '<img src="<?=pm_Context::getBaseUrl()?>/images/busy32.gif" width="30px" height="30px" />' +
            '<div class="secw-state-busy"><?=$this->lmsg('controllers.system.busy')?></div>';
    }
</script>

<div class="secw-tab-content">
    <div class="secw-settings">
        <form method="post" id="secw-settings-form" class="secw-settings-form">
            <table class="secw-settings-table">

                <tr class="<?=$this->isHttp2Enabled ? 'secw-settings-enabled' : 'secw-settings-disabled' ?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/logo-http2.png" alt="http2-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if (!$this->isNginxInstalled): ?>
                            <a class="secw-link-button" href="/admin/update/product/" target="_blank" title="<?=$this->lmsg('controllers.system.aiDesc')?>">
                                <?=$this->lmsg('controllers.system.aiButton')?>
                            </a>
                        <?php elseif (!$this->isNginxEnabled): ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.nginxDesc')?>" name="btn_nginx_enable" value="<?=$this->lmsg('controllers.system.nginxButton')?>" class="secw-link-button" onclick="show_busy('secw-http2-state');" />
                        <?php elseif ($this->isHttp2Enabled): ?>
                            <span title="<?=$this->lmsg('controllers.system.http2Desc')?>">
                                <?=$this->lmsg('controllers.system.http2Enabled')?>
                            </span>
                        <?php else: ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.http2Desc')?>" name="btn_http2_enable" value="<?=$this->lmsg('controllers.system.http2Button')?>" class="secw-link-button" onclick="show_busy('secw-http2-state');" />
                        <?php endif ?>
                    </td>
                    <td id='secw-http2-state'>
                        <?php if ($this->isHttp2Enabled): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateEnabled')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateDisabled')?></div>
                        <?php endif ?>
                    </td>
                </tr>

                <tr class="<?=$this->isPanelSecured ? 'secw-settings-enabled' : 'secw-settings-disabled'?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/logo-sslcert.png" alt="secure-panel-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if ($this->isPanelSecured): ?>
                            <?=$this->lmsg('controllers.system.panelSecured')?>
                        <?php elseif (!$this->isLetsencryptInstalled): ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.letsencryptDesc')?>" name="btn_letsencrypt_install" value="<?=$this->lmsg('controllers.system.letsencryptInstall')?>" class="secw-link-button" onclick="show_busy('secw-secure-panel-state');" />
                        <?php else: ?>
                            <a href="<?=$this->securePanelFormUrl?>" title="<?=$this->lmsg('controllers.system.secureDesc')?>">
                                <?=$this->lmsg('controllers.system.panelNotSecured')?>
                            </a>
                        <?php endif ?>
                    </td>
                    <td id='secw-secure-panel-state'>
                        <?php if ($this->isPanelSecured): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateEnabled')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateDisabled')?></div>
                        <?php endif ?>
                    </td>
                </tr>

                <?php if (!$this->isKernelPatchingToolInstalled): ?>

                <?php if ($this->isKernelPatchingToolAvailable): ?>
                <tr class="secw-settings-disabled group-item-first">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$this->firstAvailableKernelPatchingTool->getLogoFileName()?>" alt="<?=$this->firstAvailableKernelPatchingTool->getDisplayName()?>" width="60px" height="60px" />
                    </td>
                    <td>
                        <input
                            type="submit"
                            title="<?=$this->firstAvailableKernelPatchingTool->getDescription()?>"
                            name="btn_<?=$this->firstAvailableKernelPatchingTool->getName()?>_install"
                            value="<?=$this->lmsg('controllers.system.kernelPatchingToolInstall', ['name' => $this->firstAvailableKernelPatchingTool->getDisplayName()])?>"
                            class="secw-link-button" onclick="show_busy('secw-kernel-patching-tool-state');"
                        />
                    </td>
                    <td rowspan="<?=(sizeof($this->restAvailableKernelPatchingTools) + 2)?>" id="secw-kernel-patching-tool-state">
                        <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                        <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
                    </td>
                </tr>
                <?php if ($this->isSeveralKernelPatchingToolAvailable): ?>
                <?php foreach ($this->restAvailableKernelPatchingTools as $tool): ?>
                <tr class="secw-settings-disabled group-item">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$tool->getLogoFileName()?>" alt="<?=$tool->getDisplayName()?>" width="60px" height="60px" />
                    </td>
                    <td>
                        <input
                            type="submit"
                            title="<?=$tool->getDescription()?>"
                            name="btn_<?=$tool->getName()?>_install"
                            value="<?=$this->lmsg('controllers.system.kernelPatchingToolInstall', ['name' => $tool->getDisplayName()])?>"
                            class="secw-link-button" onclick="show_busy('secw-kernel-patching-tool-state');"
                        />
                    </td>
                </tr>
                <?php endforeach ?>
                <?php endif ?>
                <tr class="secw-settings-disabled group-item">
                    <td></td>
                    <td>
                        <?php if ($this->isSeveralKernelPatchingToolAvailable): ?>
                            <div class="first"><?=$this->lmsg('controllers.system.kernelPatchingToolSeveralDescription', ['kernelRelease' => $this->kernelRelease])?></div>
                            <div><?=$this->lmsg('controllers.system.kernelPatchingToolSeveralWarning')?></div>
                        <?php else: ?>
                            <div class="first"><?=$this->lmsg('controllers.system.kernelPatchingToolSingleDescription', ['kernelRelease' => $this->kernelRelease])?></div>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endif ?>

                <?php else: ?>

                <?php foreach($this->installedKernelPatchingTools as $tool): ?>
                <tr class="secw-settings-enabled">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$tool->getLogoFileName()?>" alt="<?=$tool->getDisplayName()?>" width="60px" height="60px" />
                    </td>
                    <td>
                        <a href="/modules/<?=$tool->getName()?>" title="<?=$tool->getDescription()?>">
                            <?=$this->lmsg('controllers.system.kernelPatchingToolInstalled', ['name' => $tool->getDisplayName()])?>
                        </a>
                    </td>
                    <td id='secw-patchman-state'>
                        <?php if ($tool->isActive()): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                            <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                        <?php endif ?>
                    </td>
                </tr>
                <? endforeach ?>

                <?php endif ?>

                <tr class="<?=$this->isDatagridInstalled ? 'secw-settings-enabled' : 'secw-settings-disabled'?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/logo-datagrid.png" alt="datagrid-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if ($this->isDatagridInstalled && $this->isDatagridActive): ?>
                            <a href="/modules/dgri" title="<?=$this->lmsg('controllers.system.datagridDesc')?>">
                                <?=$this->lmsg('controllers.system.datagrid')?>
                            </a>
                        <?php elseif ($this->isDatagridInstalled): ?>
                            <a href="/modules/dgri" title="<?=$this->lmsg('controllers.system.datagridDesc')?>">
                                <?=$this->lmsg('controllers.system.datagridActivate')?>
                            </a>
                        <?php else: ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.datagridDesc')?>" name="btn_datagrid_install" value="<?=$this->lmsg('controllers.system.datagridInstall')?>" class="secw-link-button" onclick="show_busy('secw-datagrid-state');" />
                        <?php endif ?>
                    </td>
                    <td id='secw-datagrid-state'>
                        <?php if ($this->isDatagridInstalled && $this->isDatagridActive): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                        <?php elseif ($this->isDatagridInstalled): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                            <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
                        <?php endif ?>
                    </td>
                </tr>

                <tr class="<?=$this->isPatchmanInstalled ? 'secw-settings-enabled' : 'secw-settings-disabled'?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/logo-patchman.png" alt="patchman-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if ($this->isPatchmanInstalled && $this->isPatchmanActive): ?>
                            <a href="/modules/patchmaninstaller" title="<?=$this->lmsg('controllers.system.patchmanDesc')?>">
                                <?=$this->lmsg('controllers.system.patchman')?>
                            </a>
                        <?php elseif ($this->isPatchmanInstalled): ?>
                            <a href="/modules/patchmaninstaller" title="<?=$this->lmsg('controllers.system.patchmanDesc')?>">
                                <?=$this->lmsg('controllers.system.patchmanActivate')?>
                            </a>
                        <?php else: ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.patchmanDesc')?>" name="btn_patchman_install" value="<?=$this->lmsg('controllers.system.patchmanInstall')?>" class="secw-link-button" onclick="show_busy('secw-patchman-state');" />
                        <?php endif ?>
                    </td>
                    <td id='secw-patchman-state'>
                        <?php if ($this->isPatchmanInstalled && $this->isPatchmanActive): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                        <?php elseif ($this->isPatchmanInstalled): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                            <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
                        <?php endif ?>
                    </td>
                </tr>

                <tr class="<?=$this->isGoogleAuthenticatorInstalled ? 'secw-settings-enabled' : 'secw-settings-disabled'?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>images/google-authenticator-64x64.png" alt="googleauthenticator-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if ($this->isGoogleAuthenticatorInstalled && $this->isGoogleAuthenticatorActive): ?>
                            <a href="/modules/google-authenticator" title="<?=$this->lmsg('controllers.system.googleauthenticatorDesc')?>">
                                <?=$this->lmsg('controllers.system.googleauthenticator')?>
                            </a>
                        <?php elseif ($this->isGoogleAuthenticatorInstalled): ?>
                            <a href="/modules/google-authenticator" title="<?=$this->lmsg('controllers.system.googleauthenticatorDesc')?>">
                                <?=$this->lmsg('controllers.system.googleauthenticatorActivate')?>
                            </a>
                        <?php else: ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.googleauthenticatorDesc')?>" name="btn_googleauthenticator_install" value="<?=$this->lmsg('controllers.system.googleauthenticatorInstall')?>" class="secw-link-button" onclick="show_busy('secw-googleauthenticator-state');" />
                        <?php endif ?>
                    </td>
                    <td id='secw-googleauthenticator-state'>
                        <?php if ($this->isGoogleAuthenticatorInstalled && $this->isGoogleAuthenticatorActive): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                        <?php elseif ($this->isGoogleAuthenticatorInstalled): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                            <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
                        <?php endif ?>
                    </td>
                </tr>

                <?php if ($this->showSymantecPromotion): ?>
                <tr class="<?=$this->isSymantecInstalled ? 'secw-settings-enabled' : 'secw-settings-disabled'?>">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>images/symantec-64x64.png" alt="symantec-logo" width="60px" height="60px" />
                    </td>
                    <td>
                        <?php if ($this->isSymantecInstalled && $this->isSymantecActive): ?>
                            <a href="/modules/symantec" title="<?=$this->lmsg('controllers.system.symantecDesc')?>">
                                <?=$this->lmsg('controllers.system.symantec')?>
                            </a>
                        <?php elseif ($this->isSymantecInstalled): ?>
                            <a href="/modules/symantec" title="<?=$this->lmsg('controllers.system.symantecDesc')?>">
                                <?=$this->lmsg('controllers.system.symantecActivate')?>
                            </a>
                        <?php else: ?>
                            <input type="submit" title="<?=$this->lmsg('controllers.system.symantecDesc')?>" name="btn_symantec_install" value="<?=$this->lmsg('controllers.system.symantecInstall')?>" class="secw-link-button" onclick="show_busy('secw-symantec-state');" />
                        <?php endif ?>
                    </td>
                    <td id='secw-symantec-state'>
                        <?php if ($this->isSymantecInstalled && $this->isSymantecActive): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                            <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                        <?php elseif ($this->isSymantecInstalled): ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                            <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                        <?php else: ?>
                            <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                            <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endif ?>
            </table>
        </form>
    </div>
</div>
