<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<?php echo $this->renderTabs($this->tabs); ?>

<script type="text/javascript">
    function show_busy(eid) {
        var e = document.getElementById(eid);
        e.innerHTML = '<img src="<?=pm_Context::getBaseUrl()?>/images/busy32.gif" width="30px" height="30px" />' +
            '<div class="secw-state-busy"><?=$this->lmsg('controllers.system.busy')?></div>';
    }
</script>

<div class="secw-tab-content">
    <div class="secw-settings">
        <form method="post" id="secw-settings-form" class="secw-settings-form">
            <table class="secw-settings-table">
                <?php if (\pm_ProductInfo::isUnix()): ?>
                    <?php include 'system/http2.phtml'; ?>
                <?php endif ?>

                <?php if (\pm_ProductInfo::isUnix()
                    || version_compare(\Modules_SecurityAdvisor_Helper_Utils::getOsVersion(), '6.3') >= 0):
                ?>
                    <?php include 'system/panel-secured.phtml'; ?>
                <?php endif ?>

                <?php if (\pm_ProductInfo::isUnix()): ?>
                    <?php include 'system/kernel-patching.phtml'; ?>
                    <?php include 'system/opsani.phtml'; ?>
                    <?php include 'system/patchman.phtml'; ?>
                <?php endif ?>

                <?php include 'system/google-auth.phtml'; ?>

                <?php if ($this->showSymantecPromotion): ?>
                    <?php include 'system/symantec.phtml'; ?>
                <?php endif ?>
            </table>
        </form>
    </div>
</div>
