<?php if ($this->isKernelPatchingToolInstalled && !$this->installedKernelPatchingToolIsUnavailable): ?>
    <?php foreach($this->installedKernelPatchingTools as $tool): ?>
        <tr class="secw-settings-enabled">
            <td>
                <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$tool->getLogoFileName()?>" alt="<?=$tool->getDisplayName()?>" width="60px" height="60px" />
            </td>
            <td>
                <a href="/modules/<?=$tool->getName()?>" title="<?=$tool->getDescription()?>">
                    <?=$this->lmsg('controllers.system.kernelPatchingToolInstalled', ['name' => $tool->getDisplayName()])?>
                </a>
            </td>
            <td id='secw-kernel-patching-tool-state'>
                <?php if ($tool->isActive()): ?>
                    <img src="<?=pm_Context::getBaseUrl()?>/images/icon-ready.png" width="30px" height="30px" />
                    <div class="secw-state-ready"><?=$this->lmsg('controllers.system.stateRunning')?></div>
                <?php else: ?>
                    <img src="<?=pm_Context::getBaseUrl()?>/images/icon-partial.png" width="30px" height="30px" />
                    <div class="secw-state-partial"><?=$this->lmsg('controllers.system.stateNotActivated')?></div>
                <?php endif ?>
            </td>
        </tr>
    <? endforeach ?>
<?php else: ?>
    <?php if ($this->isKernelPatchingToolAvailable): ?>
        <tr class="secw-settings-disabled group-item-first">
            <td>
                <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$this->firstAvailableKernelPatchingTool->getLogoFileName()?>"
                     alt="<?=$this->firstAvailableKernelPatchingTool->getDisplayName()?>" width="60px" height="60px" />
            </td>
            <td>
                <?php
                $buttonValue = $this->installedKernelPatchingToolIsUnavailable
                    ? $this->lmsg('controllers.system.kernelPatchingToolReplace', [
                        'old' => implode(', ', array_map(function ($tool) {
                            return $tool->getDisplayName();
                        }, $this->installedUnavailable)),
                        'new' => $this->firstAvailableKernelPatchingTool->getDisplayName(),
                    ])
                    : $this->lmsg('controllers.system.kernelPatchingToolInstall', [
                        'name' => $this->firstAvailableKernelPatchingTool->getDisplayName(),
                    ]);
                $buttonName = 'btn_' . $this->firstAvailableKernelPatchingTool->getName() . '_'
                    . ($this->installedKernelPatchingToolIsUnavailable ? 'replace' : 'install')
                ?>
                <input
                    type="submit"
                    title="<?=$this->firstAvailableKernelPatchingTool->getDescription()?>"
                    name="<?=$buttonName?>"
                    value="<?=$buttonValue?>"
                    class="secw-link-button" onclick="show_busy('secw-kernel-patching-tool-state');"
                />
            </td>
            <td rowspan="<?=(sizeof($this->restAvailableKernelPatchingTools) + 2)?>" id="secw-kernel-patching-tool-state">
                <img src="<?=pm_Context::getBaseUrl()?>/images/icon-not-ready.png" width="30px" height="30px" />
                <div class="secw-state-not-ready"><?=$this->lmsg('controllers.system.stateNotInstalled')?></div>
            </td>
        </tr>
        <?php if ($this->isSeveralKernelPatchingToolAvailable): ?>
            <?php foreach ($this->restAvailableKernelPatchingTools as $tool): ?>
                <tr class="secw-settings-disabled group-item">
                    <td>
                        <img src="<?=pm_Context::getBaseUrl()?>/images/<?=$tool->getLogoFileName()?>" alt="<?=$tool->getDisplayName()?>"
                             width="60px" height="60px" />
                    </td>
                    <td>
                        <input
                            type="submit"
                            title="<?=$tool->getDescription()?>"
                            name="btn_<?=$tool->getName()?>_install"
                            value="<?=$this->lmsg('controllers.system.kernelPatchingToolInstall', ['name' => $tool->getDisplayName()])?>"
                            class="secw-link-button" onclick="show_busy('secw-kernel-patching-tool-state');"
                        />
                    </td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
        <tr class="secw-settings-disabled group-item">
            <td></td>
            <td>
                <?php if ($this->isSeveralKernelPatchingToolAvailable): ?>
                    <div class="first"><?=$this->lmsg('controllers.system.kernelPatchingToolSeveralDescription', ['kernelRelease' => $this->kernelRelease])?></div>
                    <div><?=$this->lmsg('controllers.system.kernelPatchingToolSeveralWarning')?></div>
                <?php else: ?>
                    <div class="first"><?=$this->lmsg('controllers.system.kernelPatchingToolSingleDescription', ['kernelRelease' => $this->kernelRelease])?></div>
                <?php endif ?>
                <?php foreach ($this->installedUnavailable as $tool): ?>
                    <div class="first"><?=$tool->getDescription()?></div>
                <?php endforeach ?>
            </td>
        </tr>
    <?php endif ?>
<?php endif ?>
